### ISSUE TITLE
Use GitHub actions to manage releases

### ISSUE THREAD

**Issue by nandgator** [sarathsajan/photomosaic_generator#1]
Hey, I saw you create [another repository](https://github.com/sarathsajan/photomosaic_generator_executable) for releases. I think... a better way would be to use actions from marketplace.

Here's one you may wanna try: https://github.com/marketplace/actions/upload-a-release-asset

**Comment by nandgator** [comment]
Or I think you can do this also: https://github.com/sarathsajan/photomosaic_generator/releases/new. Better manual. Not automated.

**Comment by sarathsajan** [comment]
Thanks but I will probably scrap the the idea of executable
